Add rsync build
This rsync build has no openssl support because AWS-LC does not
provide md5 features:

    In file included from ./rsync.h:1118,
                     from ./simd-checksum-x86_64.cpp:57:
    ./lib/mdigest.h:4:10: fatal error: openssl/sha.h: No such file or directory
        4 | #include <openssl/sha.h>
          |          ^~~~~~~~~~~~~~~
    compilation terminated.
    If you can't fix the issue, re-run ./configure with --disable-roll-simd.
    make: *** [Makefile:153: simd-checksum-x86_64.o] Error 1
    make: *** Waiting for unfinished jobs....

rsync is not built against system libraries to prevent from a naming
clash between system and AWS-LC libs.

This should not be a big deal if rsync is not meant to be used over
SSL.

Signed-off-by: Sébastien Gross <seb•ɑƬ•chezwam•ɖɵʈ•org>